"""Add favorites_count def value 0

Revision ID: 00d9934612a3
Revises: 8d08e6234bdc
Create Date: 2024-02-15 03:47:37.844239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d9934612a3'
down_revision = '8d08e6234bdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.TEXT(length=150),
               type_=sa.String(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(length=150),
               existing_nullable=True)

    # ### end Alembic commands ###
