"""delete field for mail auth

Revision ID: 278493ac1ffa
Revises: 4bd65d95056d
Create Date: 2024-02-23 00:06:01.156784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278493ac1ffa'
down_revision = '4bd65d95056d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('access')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
