"""Add category column to product

Revision ID: 72e47b187bec
Revises: 7f7dc57ec07c
Create Date: 2024-02-14 04:31:52.511745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e47b187bec'
down_revision = '7f7dc57ec07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('new_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_category', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), server_default=sa.text("'unknown'"), nullable=False))

    # ### end Alembic commands ###
