"""empty message

Revision ID: 7f7dc57ec07c
Revises: a451f180ce27
Create Date: 2024-02-14 03:35:07.269635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7dc57ec07c'
down_revision = 'a451f180ce27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_category', sa.String(length=50)))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('new_category')

    # ### end Alembic commands ###
