"""Add favorites_count column to User model

Revision ID: 8d08e6234bdc
Revises: 9592d0bbfcf3
Create Date: 2024-02-15 03:43:11.454654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d08e6234bdc'
down_revision = '9592d0bbfcf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorites_count')

    # ### end Alembic commands ###
