"""empty message

Revision ID: a451f180ce27
Revises: 
Create Date: 2024-02-12 17:58:27.483131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a451f180ce27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.String(length=255), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###
